### ISSUE TITLE
Add global rate limit

### ISSUE THREAD

**Issue by Micophi** [Micophi/dnscheck#1]
Add a global rate limit in the dnscheck.yaml configuration file. This rate limit will be split evenly accross all DNS servers.
Exception, dns server defined with their own rate limit.

```yaml
---
dnsservers:
  rateLimit: 20
  - name: Quad9
    description: Malware Blocking, DNSSEC Validation
    ip: 9.9.9.9
    rateLimit: 5
```
